sudo: required
services:
  - docker

before_install:
  - docker build -t macmurph42/docker-react -f Dockerfile.dev .

script:
  - docker run macmurph42/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-605606713979"
  bucket_path: "docker-react"
  on:
    branch: master